---
 - hosts: localhost
   connection: local
   user: root
   become: yes

   tasks:
    - name: Getting the Public IP of the ec2 web servers
      shell: aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag-value,Values=client" --output text --query "Reservations[*].Instances[*].{ID:PublicIpAddress}"
      register: pubIPs

    - name: Create SSH Group to login dynamically to EC2 Instance(s)
      add_host:
       hostname: "{{item}}"
       groups: tag_ServType_client ##### This is the dynamic host group created
      with_items: "{{pubIPs.stdout_lines|list}}"
   
 - hosts: nagios
   remote_user: ec2-user
   become: yes
   gather_facts: true
   roles:
   - nagiosservers


