---
 - hosts: localhost
   connection: local
   become: yes
   roles:
   - common

   tasks:
    - name: Getting the Public IP of the ec2 web servers
      shell: aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag-value,Values=http" --output text --query "Reservations[*].Instances[*].{ID:PublicIpAddress}"
      register: pubIPs
 
    - name: Create the dynamic group of the EC2 Instance(s)
      add_host:
       hostname: "{{item}}"
       groups: tag_Name_http ##### This is the dynamic host group created
      with_items: "{{pubIPs.stdout_lines|list}}"

    - name: Getting the Public IP of the all ec2 servers for adding into nagios
      shell: aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag-value,Values=client" --output text --query "Reservations[*].Instances[*].{ID:PublicIpAddress}"
      register: pubNagIPs
 
    - name: Create the dynamic group of all the EC2 Instances to be added in Nagios
      add_host:
       hostname: "{{item}}"
       groups: tag_ServType_client ##### This is the dynamic host group created
      with_items: "{{pubNagIPs.stdout_lines|list}}"


######## Http Setup ###########
 - hosts: tag_Name_http
   remote_user: ec2-user
   become: yes
   gather_facts: false
   roles:
   - webservers

####### Nagios Setup ############
 - hosts: nagios
   remote_user: ec2-user
   become: yes
   gather_facts: false
   roles:
   - nagiosservers

