---
 - hosts: localhost
   connection: local
   user: root
   become: yes

   tasks:
    - name: Shelling out the public dns
      shell: aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=tag-value,Values=http" --output text --query "Reservations[*].Instances[*].{ID:PublicIpAddress}"
      register: pubIPs

    - name: Create SSH Group to login dynamically to EC2 Instance(s)
      add_host:
       hostname: "{{item}}"
       groups: dynamic_webservers ##### This is the dynamic host group created
      with_items: "{{pubIPs.stdout_lines|list}}"

 - hosts: dynamic_webservers
   remote_user: ec2-user
   become: yes
   gather_facts: false
   roles:
   - webservers


