---
 - name: Copy the rpm file "{{ nameoftherpm }}" to the destination server
   copy:
    src: /opt/ansible-workbook/roles/upc/files/cofnigs/cmdc/{{ nameoftherpm }}.rpm
    dest: /opt/nds/rpms/
 
 - name: Install the copied rpm {{ nameoftherpm }}
   yum:
    name: /opt/nds/rpms/{{ nameoftherpm }}.rpm
    state: present
 
 - name: Transfer the config file to the remote location
   file:
    src: configs/cmdc/"config.properties-{{ nameofinstalleddir }}"
    dest: /opt/nds/installed/{{ nameofinstalleddir }}/etc/config.properties
    owner: "{{ ndsusername }}"
    group: "{{ ndsgroupname }}"
    mode: 0655
 
 - name: Stop the running service {{ servicenameofcomponent }}
   service:
    name: "{{ servicenameofcomponent }}"
    state: stopped
 
 - name: Unlink and link (or) change the link of the currently installed component
   file:
    src: /opt/nds/installed/{{ nameofinstalleddir }}
    dest: /opt/nds/{{ linknameofservice }}
    state: link
    mode: 0777
   notify: 
    - Restart "{{ servicenameofcomponent }}"
    
