---

 - name: Enforce System tools Package are present
   yum:  
    name: "{{item}}"
    state: latest
   with_items: 
     - nmap
     - telnet
     - screen
     - tree

 - name: Update all the packages to the latest
   yum: 
    name: "*"
    state: latest

 - name: Install Apache
   yum:
    name: httpd
    state: latest

 - name: Copy the index.html file to the location
   template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: 0755
   notify:
     - Restart httpd

 - name: Stop the firewall service
   service:
    name: iptables
    state: stopped
    enabled: no

