---
 - name: Update all the packages to the latest
   yum: 
    name: "*"
    state: latest

 - name: Install Apache
   yum:
    name: httpd
    state: latest

 - name: Copy the index.html file to the location
   file: 
    src: index.html
    dest: /var/www/html/
    mode: 0755
   notify:
    - Restart Apache

 - name: Stop the firewall service
   service:
    name: iptables
    state: stopped
    enabled: no

 - name: Make sure selinux is disabled
   selinux:
    state: disabled 
