---
 secGroupWeb: "webgroup"
 secGroupDB: "dbgroup"
 secGroupNagios: "nagiosgroup"
 regionDefault: "us-east-1"
 zonesDefault: ['us-east-1a', 'us-east-1b']
 instanceType: "t2.micro"
 keyPairName: "ec2all"
 elbNameWeb: "HTTPLoadBalancer"
 elbProtocol: "http"
 elbLBport: "80"
 elbInstPort: "80"

 ec2_instances:
   ### This is for host1
    - name: "web1"
      image: "ami-0b33d91d" # Amazon Linux
      tags: '{"Name":"web1","Type":"http","ServType":"client"}'
      group: '{"webgroup","nagiosgroup"}'
      zone: us-east-1a
    ### This is for host2
    - name: "web2"
      image: "ami-0b33d91d" ## Amazon Linux
      tags: '{"Name":"web2","Type":"http","ServType":"client"}'
      group: '{"webgroup","nagiosgroup"}'
      zone: us-east-1a
    ### This is for host3
    - name: "web3"
      image: "ami-0b33d91d" ## Amazon Linux
      tags: '{"Name":"web3","Type":"http","ServType":"client"}'
      group: '{"webgroup","nagiosgroup"}'
      zone: us-east-1b
    ### This is for host4
    - name: "web2"
      image: "ami-0b33d91d" ## Amazon Linux
      tags: '{"Name":"web4","Type":"http","ServType":"client"}'
      group: '{"webgroup","nagiosgroup"}'
      zone: us-east-1b



