---
 ec2_instances:
   ### This is for host1
    - name: "web1"
      image: "ami-0b33d91d" # Amazon Linux
      tags: '{"Name":"web1","Type":"http"}'
      group: 'webgroup' # 
      zone: us-east-1a
    ### This is for host2
    - name: "web2"
      image: "ami-0b33d91d" ## Amazon Linux
      tags: '{"Name":"web2"}'
      group: 'webgroup' #
      zone: us-east-1b
