---
 - name: This module is to install the basic required package in the NAGIOS server
   yum:
    name: "{{ item }}"
    state: latest
   with_items:
     - httpd
     - php
     - gcc
     - glibc
     - glibc-common
     - gd
     - gd-devel
   when:
     - nagios_master == "master"

 - debug:msg="The value of nagios_master is {{ nagios_master }}"

 - name: Installing the nagios nagios-plugins  package
   yum:
    name: "{{ item }}"
    enablerepo: epel
   with_items:
     - nagios
     - nagios-plugins
   when:
     - rnagios_master == "master"

 - name: Adding the group nagcmd
   group:
    name: nagcmd
    state: present   
 
 - name: Create user nagios and add group nagcmd
   user:
    name: nagios
    comment: "This is  nagios user"
    group: nagcmd
    state: present
   when:
     - nagios_master == "master"

 - name: Adding user acpache to nagcmd group
   user:
    name: apache
    groups: nagcmd
   when:
     - nagios_master == "master"

 - name: Next change the admins email address to appropiately in the contacts.cfg
   template:
    src: templates/contacts.cfg.j2
    dest: /etc/nagios/objects/contacts.cfg
    owner: nagios
    group: nagcmd
   when:
     - nagios_master == "master"

 - name: Copy the nagios.conf to the respective location
   template:
    src: templates/nagios.conf.j2
    dest: /etc/httpd/conf.d/nagios.conf
    owner: apache
    group: apache
   when:
     - nagios_master == "master"

 - name: Setting password for the user Nagios Admin
   htpasswd:
    path: /etc/nagios/passwd
    name: nagiosadmin
    password: 'nagiosadmin'
    owner: root
    group: apache
    mode: 0640
   when:
     - nagios_master == "master"

 - name: Copy the nagios.cfg to the respective location
   template:
    src: templates/nagios.cfg.j2
    dest: /etc/nagios/nagios.cfg
    owner: apache
    group: apache
   when:
     - nagios_master == "master"

 - name: Copy the commands.cfg(file to create the real command to be executed on server) to the respective location
   template:
    src: templates/commands.cfg.j2
    dest: /etc/nagios/objects/commands.cfg
    owner: root
    group: nagcmd
   when:
     - nagios_master == "master"

 - name: Make sure the directory for placing the servers config mentioned in the nagios.cfg is present
   file: 
    path: /etc/nagios/servers/
    state: directory
    group: nagcmd
    mode: 0750
   when:
     - nagios_master == "master"

 - name: Copy the client cfg file which has the parameters of what to be checked
   template:
    src: templates/clientname.cfg.j2
    dest: /etc/nagios/servers/"{{ ansible_hostname }}".cfg

 - name: Enabling boot time on and restarting the Nagios and Httpd service
   service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
   with_items:
     - nagios
     - httpd
   when:
     - nagios_master == "master"

 - name: Install the client side rpms nrpe
   yum:  
    name: "{{ item }}"
    state: latest
   with_items:
     - nrpe
     - nagios-plugins 

 - name: Copt the nrpe file to client machine
   template:
    src: templates/nrpe.cfg.j2
    dest: /etc/nagios/nrpe.cfg

 - name: Next Enable the service on boot up and restart the service
   yum:
    name: nrpe
    enabled: yes
    state: restarted
     
